schema = 3

[mod]
  [mod."github.com/KarpelesLab/weak"]
    version = "v0.1.1"
    hash = "sha256-VaekSfWKmcdHnfeBM5T4yG0cku3LHS5lDRNyHAloXso="
  [mod."github.com/alecthomas/chroma"]
    version = "v0.10.0"
    hash = "sha256-p721vddVTv4iv1O0/dqpdk5xF6x9iLIHcrfh8JEVnqQ="
  [mod."github.com/alessio/shellescape"]
    version = "v1.4.1"
    hash = "sha256-rTWqbtC+EVz4fT2HmDWpucUTMtQyraInPYf2hlG8/pM="
  [mod."github.com/danieljoos/wincred"]
    version = "v1.1.0"
    hash = "sha256-sW90eNnxmYBGY+uQe9tH97CCHdRvNuseWhicySnKlDo="
  [mod."github.com/diamondburned/adaptive"]
    version = "v0.0.2-0.20221227093656-fa139be203a8"
    hash = "sha256-xIerrbYQf6FPbbRd60OnBStIJMl6mg/Qvl+LTmRbyIw="
  [mod."github.com/diamondburned/arikawa/v3"]
    version = "v3.3.5"
    hash = "sha256-diP4y1hCMNrGNpnHVWBjbwiDmPF0LJx9K6os1sy36i4="
  [mod."github.com/diamondburned/chatkit"]
    version = "v0.0.0-20240214131532-4b8acdf0f84b"
    hash = "sha256-RWITh+L4dR1cPKgM0LTCsIXC2d81yaqspK0zQFPjaBo="
  [mod."github.com/diamondburned/gotk4-adwaita/pkg"]
    version = "v0.0.0-20240107232253-5f283b5d35bc"
    hash = "sha256-ktoJxbdnDWTrGIKkzEg1yxe4xnklqTggBZUTFYtu62Y="
  [mod."github.com/diamondburned/gotk4/pkg"]
    version = "v0.2.2"
    hash = "sha256-wyGZ+QNlDGB7A9TvotMhUefq28KBUPqIMfcVs8cHHj0="
  [mod."github.com/diamondburned/gotkit"]
    version = "v0.0.0-20240420000353-b561f0555aad"
    hash = "sha256-7mq4unvIiTq+d81rJCggAqRl3N1ljXeAPrLvU0reBrQ="
  [mod."github.com/diamondburned/ningen/v3"]
    version = "v3.0.1-0.20240215053437-0d35ff052647"
    hash = "sha256-qIMBPiaXGjVoe3wc0U5T36b8WMknnRs55wPnjy/+zTE="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.4.0"
    hash = "sha256-Pk/S2x2rX7xnGFLyoHEw09CoNQimvz/msdPRsxLaLsc="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.0"
    hash = "sha256-gy4G1PnHD9iw2MitHX6y1y93qr3C9IncmXL7ttUMDs8="
  [mod."github.com/enescakir/emoji"]
    version = "v1.0.0"
    hash = "sha256-fnYYIR2EQG7CfdEdY8Mui2wVTmrcd0KhZD+SZLXT0fY="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.0.6"
    hash = "sha256-fpaNRLf+qZy6Sk3Uas2H9fpxkVNkOCY1EcHcIZCAPr8="
  [mod."github.com/gorilla/schema"]
    version = "v1.2.0"
    hash = "sha256-fENDYTtMBGAgJB7rv0o61KyoO81mibJycLifazazd1E="
  [mod."github.com/gorilla/websocket"]
    version = "v1.4.2"
    hash = "sha256-GhBLM/XTm2lFCyDvJbnCLAI2OyYXQV6W+jRPOQ1PdVY="
  [mod."github.com/ianlancetaylor/cgosymbolizer"]
    version = "v0.0.0-20220405231054-a1ae3e4bba26"
    hash = "sha256-gQ5SUjHpX82+Eke8znuweBL/yzaVQQV06eLH91gTfcI="
  [mod."github.com/leonelquinteros/gotext"]
    version = "v1.5.3-0.20230829162019-37f474cfb069"
    hash = "sha256-ylBa3NtdtkgqEAhsXdYBTyhUUSU7e5NpHfw6Wq7cwbU="
  [mod."github.com/lmittmann/tint"]
    version = "v1.0.4"
    hash = "sha256-xLaS+fcxmjsoOC3I5IX4jWkmgPVUFJBKEK+jgY5AFa0="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/sahilm/fuzzy"]
    version = "v0.1.0"
    hash = "sha256-69GT+9rw7Wzdn1QDUoC5oFsEjf378N14yHDKhxfN3PQ="
  [mod."github.com/twmb/murmur3"]
    version = "v1.1.3"
    hash = "sha256-3r/AQgj6Xw4GczIkwmX2JPOM8qqH6Oh5oUM4P/lVMQM="
  [mod."github.com/yalue/merged_fs"]
    version = "v1.2.3"
    hash = "sha256-qj+AMOjdFRFoUj9KIKLIBd3DenicUtF2tBEWYZ5zyIY="
  [mod."github.com/yuin/goldmark"]
    version = "v1.5.6"
    hash = "sha256-+yAEKuRtXHX2THh3XMSG6UPcPPU0sSz5H5taH9Mx1Jc="
  [mod."github.com/zalando/go-keyring"]
    version = "v0.2.1"
    hash = "sha256-F4G03wV1GeLucqJIOXVN4htEETfGzIVAsBTU1iNLxlA="
  [mod."go4.org"]
    version = "v0.0.0-20200411211856-f5505b9728dd"
    hash = "sha256-UxbUjyr/bArM+3XAQfQ58XBbePvUdZ31EiQkCfXl/i0="
  [mod."go4.org/unsafe/assume-no-moving-gc"]
    version = "v0.0.0-20231121144256-b99613f794b6"
    hash = "sha256-p0bcawoazS5r49P8Ru0anJ5crNB0+3xGtzZNpCAe3gI="
  [mod."golang.org/x/crypto"]
    version = "v0.17.0"
    hash = "sha256-/vzBaeD/Ymyc7cpjBvSfJfuZ57zWa9LOaZM7b33eIx0="
  [mod."golang.org/x/image"]
    version = "v0.0.0-20220902085622-e7cb96979f69"
    hash = "sha256-yVdEVP3jBVOYd4ADvz9UHQfju9Hhh9Xr9TE9kfHJGbw="
  [mod."golang.org/x/sync"]
    version = "v0.1.0"
    hash = "sha256-Hygjq9euZ0qz6TvHYQwOZEjNiTbTh1nSLRAWZ6KFGR8="
  [mod."golang.org/x/sys"]
    version = "v0.15.0"
    hash = "sha256-n7TlABF6179RzGq3gctPDKDPRtDfnwPdjNCMm8ps2KY="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20210723032227-1f47c861a9ac"
    hash = "sha256-YygVh3tohBFn6Or1txGRgeaCaCoMJLhEmKaKxLkjLbc="
  [mod."libdb.so/ctxt"]
    version = "v0.0.0-20240216055249-07a499f07b78"
    hash = "sha256-bw3d7H4zeKiKuE9djkxkLwYp/09k0Tu9GM9fL3mQve0="
